[WIP]データベース設計
silk-k/chat-space pull request #1
Opened 2019-03-29 05:05 UTC by silk-k

#WHAT
チャットスペースのデータベースの設計

#WHY

2019-03-29 05:18 UTC, miyagit reviewed
DB設計がうまくいってないようなので、一度chat-spaceのDB構造や中間テーブルについてメンターに質問して理解を深めてください！

2019-03-29 05:18 UTC, miyagit commented on README.md
> +|messages_id|text|null: false, foreign_key: true|
こちら必要ないですね。

2019-03-29 08:11 UTC, silk-k commented
ありがとうございます。
修正しました。
中間テーブルのカラムの型をreferenceに変更し
カラム名もそれぞれ変更しました。

2019-03-29 10:56 UTC, silk-k commented
申し訳ありません。
再度訂正したものをお送りします。
外部キーは必要なものだけにしました。
null:falseは外部キーには必要ないと思ったので省きました。
中間テーブルのreferenceはやめてuser_idとgroup_idに再度戻しました。
勉強不足でお送りしてしまい、申し訳ありませんでした。

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +|group_name|string|null: false|
同じテーブルにuser_nameがある訳ではないので、group_nameではなく、nameで大丈夫です。

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +## users_groupテーブル
user_groupsとテーブル名は複数にしましょう！

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +- has_many :users,through: :users_group
外部キーカラムを持つのにhas_manyということはありません。もう一考お願いします。

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +|group_id|string|foreign_key: true|
String型ではないですね！

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +- has_many :users, through: :users_group
message及びuser_gruopsとのアソシエーションも追加しましょう！

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +|address|text|null: false|
adressは不要ですね！

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +|user_name|string|null: false|
こちらもnameにしましょう！

2019-03-31 02:41 UTC, kuroko918 commented on README.md
> +- has_many :groups,through: :users_group
user_gruopsとのアソシエーションも追加しましょう！

2019-03-31 02:59 UTC, silk-k commented on README.md
> +|group_name|string|null: false|
丁寧にありがとうございます。
とても分かりやすくて助かります。
nameに訂正しました。

2019-03-31 03:00 UTC, silk-k commented on README.md
> +## users_groupテーブル
ありがとうございます。
訂正しました。

2019-03-31 03:03 UTC, silk-k commented on README.md
> +- has_many :users,through: :users_group
ありがとうございます。
belong_toに訂正しました。

2019-03-31 03:06 UTC, silk-k commented on README.md
> +|group_id|string|foreign_key: true|
ありがとうございます。
user_idとgroup_idのカラムの型をintegerに変更しました。

2019-03-31 03:17 UTC, silk-k commented on README.md
> +|address|text|null: false|
ユーザー登録するときにaddressが必要だったと思うのですが
ここではいらないのでしょうか？
ということはパスワードも不要ということでしょうか？？

2019-03-31 03:17 UTC, silk-k commented on README.md
> +|user_name|string|null: false|
ありがとうございます。
訂正しました。

2019-03-31 03:23 UTC, silk-k commented on README.md
> +- has_many :groups,through: :users_group
ありがとうございます。
訂正しました。

2019-03-31 03:24 UTC, silk-k commented on README.md
> +- has_many :users, through: :users_group
ありがとうございます。
訂正いたしました。

2019-03-31 03:33 UTC, ghost requested changes

2019-03-31 03:33 UTC, hiroki5123 commented on README.md
> +
アソシエーションが一つ足りないので見直してみましょう

2019-03-31 03:33 UTC, hiroki5123 commented on README.md
> +- has_many :groups,through: :user_groups
アソシエーションが一つ足りないので見直してみましょう

2019-03-31 03:33 UTC, hiroki5123 commented on README.md
> +### Association
アソシエーションに誤りがありますので、修正をお願い致します。

2019-03-31 03:50 UTC, silk-k commented on README.md
> +
ありがとうございます。
user_groupsとのアソシエーションを追加しました。

2019-03-31 03:50 UTC, silk-k commented on README.md
> +- has_many :groups,through: :user_groups
ありがとうございます。
user_groupsとのアソシエーションを追加しました。

2019-03-31 04:03 UTC, silk-k commented on README.md
> +### Association
messageのアソシエーションは
user_groupテーブルを介さないという解釈で
userテーブルとgroupテーブルに変更しました。

2019-03-31 04:22 UTC, kuroko918 commented on README.md
> +## groupテーブル
テーブル名は複数形にしましょう！

2019-03-31 04:22 UTC, kuroko918 commented on README.md
> +## userテーブル
こちらも複数形にしましょう！

2019-03-31 04:22 UTC, kuroko918 commented on README.md
> +|group_id|integer|foreign_key: true|
integer型だとforeign_keyによる外部キー制約が効かないのでreferences型に変えましょう！

2019-03-31 04:22 UTC, kuroko918 commented on README.md
> +## messageテーブル
こちらも複数形にしましょう！

2019-03-31 04:22 UTC, kuroko918 commented on README.md
> +## user_groupテーブル
こちらもuser_groupsと複数形にしましょう！

2019-03-31 04:37 UTC, silk-k commented on README.md
> +## groupテーブル
ありがとうございます。
訂正いたしました。

2019-03-31 04:37 UTC, silk-k commented on README.md
> +## userテーブル
ありがとうございます。
訂正いたしました。

2019-03-31 04:37 UTC, silk-k commented on README.md
> +## messageテーブル
ありがとうございます。
訂正いたしました。

2019-03-31 04:37 UTC, silk-k commented on README.md
> +## user_groupテーブル
ありがとうございます。
訂正いたしました。

2019-03-31 04:42 UTC, ghost approved these changes
LGTMです！

2019-03-31 04:54 UTC, silk-k commented
ありがとうございました。

2019-04-03 07:35 UTC, merged